# CMake generated Testfile for 
# Source directory: /work1/sadasivan/student30/composable_kernel/example
# Build directory: /work1/sadasivan/student30/composable_kernel/build_new/example
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("01_gemm")
subdirs("02_gemm_bilinear")
subdirs("03_gemm_bias_relu")
subdirs("04_gemm_add_add_fastgelu")
subdirs("09_convnd_fwd")
subdirs("10_convnd_fwd_multiple_d_multiple_reduce")
subdirs("12_reduce")
subdirs("13_pool2d_fwd")
subdirs("14_gemm_quantization")
subdirs("15_grouped_gemm")
subdirs("16_gemm_multi_d_multi_reduces")
subdirs("17_convnd_bwd_data")
subdirs("18_batched_gemm_reduce")
subdirs("19_binary_elementwise")
subdirs("20_grouped_conv_bwd_weight")
subdirs("21_gemm_layernorm")
subdirs("22_cgemm")
subdirs("23_softmax")
subdirs("24_batched_gemm")
subdirs("25_gemm_bias_e_permute")
subdirs("26_contraction")
subdirs("27_layernorm")
subdirs("28_grouped_gemm_bias_e_permute")
subdirs("29_batched_gemm_bias_e_permute")
subdirs("30_grouped_conv_fwd_multiple_d")
subdirs("31_batched_gemm_gemm")
subdirs("32_batched_gemm_scale_softmax_gemm")
subdirs("33_multiple_reduce")
subdirs("34_batchnorm")
subdirs("35_splitK_gemm")
subdirs("36_sparse_embedding")
subdirs("37_batched_gemm_add_add_relu_gemm_add")
subdirs("38_grouped_conv_bwd_data_multiple_d")
subdirs("39_permute")
subdirs("40_conv2d_fwd_quantization")
subdirs("41_grouped_conv_conv_fwd")
subdirs("42_groupnorm")
subdirs("43_splitk_gemm_bias_e_permute")
subdirs("44_elementwise_permute")
subdirs("45_elementwise_normalization")
subdirs("46_gemm_add_multiply")
subdirs("47_gemm_bias_softmax_gemm_permute")
subdirs("48_pool3d_fwd")
subdirs("49_maxpool2d_bwd")
subdirs("50_put_element")
subdirs("51_avgpool3d_bwd")
subdirs("52_im2col_col2im")
subdirs("53_gemv_splitk")
subdirs("54_tall_and_skinny_gemm_splitk")
subdirs("60_gemm_multi_ABD")
subdirs("61_contraction_multi_ABD")
subdirs("62_conv_fwd_activ")
